	
	REAL FUNCTION NORMA1(X, N)
		INTEGER N
		REAL X(15)
		NORMA1 = 0
		DO I = 1, N
			NORMA1 = NORMA1 + ABS(X(I))
		ENDDO
	END	FUNCTION

	REAL FUNCTION NORMA2(X, N)
		INTEGER N
		REAL X(15)
		NORMA2 = 0
		DO I = 1, N
			NORMA2 = NORMA2 + (X(I)*X(I))
		ENDDO
		NORMA2 = SQRT(norma2)
	END	FUNCTION

	REAL FUNCTION NORMAINF(X, N)
		INTEGER N
		REAL X(15)
		REAL ABSOL
		NORMAINF = 0
		DO I = 1, N
			ABSOL = ABS(X(I))
			IF(ABSOL.GT.normainf)THEN
				NORMAINF = ABSOL
			ENDIF
		ENDDO
	END	FUNCTION

	PROGRAM CALCOLONORME
		INTEGER N
		REAL INTERVALLO, ADD, NORMA1, NORMA2, NORMAINF, N1, N2, NI
		REAL K(15)
		N = 15
		K(1) = -1
		INTERVALLO = ABS(-1) + 1
		DO I = 2, N
			ADD = INTERVALLO/(I-1)
			DO J = 2, I-1
				K(J) = K(J-1) + ADD
			ENDDO
			K(I) = 1
			N1 = NORMA1(K, I)
			N2 = NORMA2(K, I)
			NI = NORMAINF(K, I)
			WRITE(*,*) I, N1, N2, NI
			WRITE(1,*) I, N1
			WRITE(2,*) I, N2
			WRITE(3,*) I, NI
		ENDDO	
     	END	PROGRAM												 
